export const BRANDS_CARRIED = [
  "Ganni",
  "Baum und Pferdgarten",
  "Stine Goya",
  "Samsøe Samsøe",
  "Sézane",
  "Rouje Paris",
  "Isabel Marant",
  "Isabel Marant Étoile",
  "A.P.C.",
  "&Other Stories",
  "Arket",
  "COS",
  "Wood Wood",
  "Acne Studios",
  "Anine Bing",
  "Lollys Laundry",
  "Lovechild 1979",
  "Neo Noir",
  "Mads Nørgaard Copenhagen",
  "Second Female",
  "Stella Nova",
  "Beck Söndergaard",
  "Bobo Choses",
  "Brigitte Herskind",
  "Cecilie Copenhagen",
  "DAY Birger et Mikkelsen",
  "Designers Remix",
  "Envii",
  "Esmé Studio",
  "Gestuz",
  "Habiba",
  "Han Kjøbenhavn",
  "Henrik Vibskov",
  "Ichi",
  "InWear",
  "KA:NT Copenhagen",
  "Konges Sløjd",
  "Liberté Essentiel",
  "Magasin",
  "Malene Birger",
  "Mood Copenhagen",
  "MSCH Copenhagen",
  "Munthe",
  "Nümph",
  "Opera Sport",
  "Part Two",
  "Pernilla Wahlgren",
  "Pieces",
  "Pure Friday",
  "Rabens Saloner",
  "Rodebjer",
  "Rotate",
  "Sabina Sommer",
  "Sand Copenhagen",
  "Selected Femme",
  "Sissel Edelbo",
  "Sisters Point",
  "Skall Studio",
  "Sofie Schnoor",
  "Studio Feder",
  "Tiger of Sweden",
  "Trois Pommes",
  "YAS",
  "Zadig & Voltaire",
  "American Vintage",
  "Atelier Revive",
  "Boii Studios",
  "Bongusta",
  "Celine",
  "Comme des Garçons",
  "Comme des Garçons PLAY",
  "Free People",
  "IRO Paris",
  "Kenzo",
  "Marella",
  "MAX&Co",
  "MOTHER",
  "MSGM Milano",
  "Nanushka",
  "Never Fully Dressed",
  "NoaNoa",
  "Proenza Schouler",
  "Sandro Paris",
  "Scotch & Soda",
  "Sea New York",
  "See by Chloé",
  "Stella McCartney",
  "Stüssy",
  "T by Alexander Wang",
  "The Jogg Concept",
  "Topshop",
  "Tory Burch",
  "Canada Goose",
  "Carhartt",
  "Columbia",
  "Dickies",
  "Fjäll Räven",
  "Homeboy",
  "Ilse Jacobsen",
  "Karen Millen",
  "Lee",
  "Levi's",
  "Lindex",
  "Mango",
  "Monki",
  "Moves",
  "NA-KD",
  "Nike ACG",
  "Pico",
  "Ralph Lauren",
  "The North Face",
  "Urban Outfitters",
  "U.S. Polo Assn.",
  "Vila",
  "Wrangler",
  "Zara",
  "H&M Premium",
  "H&M Trend",
  "H&M Edition",
] as const;
